plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - experiment-with-the-sample-app.md
  - five-steps-to-success.md
  - go-live-checklist.md
  - sample-app.md
  - sample-use-case.md
  - sources-explained.md
  - useful-definition.md
  - we-are-here-to-help.md
  - what-can-i-do-with-intempt-patform.md
  - what-is-intempt-platform.md	restoring
  - where-do-i-start.md
